version: '3.8'

services:
  balebot:
    build: .
    container_name: bale_bot
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - .:/app
      - /etc/letsencrypt:/etc/letsencrypt:ro  # Mount SSL certificates as read-only
    environment:
      - PYTHONUNBUFFERED=1
    deploy:
      resources:
        limits:
          cpus: '0.5'        # Limit container utilization to max 80% of a single CPU core
          memory: 512M      # Limit container RAM quota to 1GB to protect the VPS from spikes